fix: update URL in pr comment

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -288,7 +288,7 @@ jobs:
                     echo "Successfully created redirect rule for PR #${PR_NUMBER}."
 
                     echo "Posting comment to PR..."
-                    gh pr comment ${PR_NUMBER} --body "🚀 Preview deployment is ready at: ${PR_NUMBER}.staging.mindvista.ca" || echo "ERROR: Failed to comment on PR. Skipping..."
+                    gh pr comment ${PR_NUMBER} --body "🚀 Preview deployment is ready [here](https://${PR_NUMBER}.staging.mindvista.ca)." || echo "ERROR: Failed to comment on PR. Skipping..."
                   else
                     echo "Redirect rule already exists. Skipping creation and comment."
                   fi
